#!/usr/bin/env bash
# Cleanup script for CI testing

# Stop existing instance of OMERO
pkill icegridnode || echo No OMERO.server running
pkill python || echo No OMERO.Web running
pgrep nginx && /usr/local/bin/nginx -c /usr/local/nginx/etc/omero.conf -s stop || echo No nginx running
pkill postgres || echo No PostgreSQL running

# Clean existing Homebrew
rm -rf /usr/local/* && rm -rf /usr/local/.git || echo No Homebrew found
rm -rf /Library/Caches/Homebrew/* || echo No Homebrew cache found