#!/usr/bin/env bash
# Cleanup script for CI testing

# Stop existing instance of OMERO
/usr/local/bin/omero web stop || echo Web stop failed.
/usr/local/bin/omero admin stop || echo Server stop failed.

# Remove dangling processes
pgrep nginx && /usr/local/bin/nginx -c /usr/local/nginx/etc/omero.conf -s stop
pgrep postgres && killall postgres

# Clean existing Homebrew
rm -rf /usr/local/* && rm -rf /usr/local/.git || echo No Homebrew found
rm -rf /Library/Caches/Homebrew/* || echo No Homebrew cache found