#!/usr/bin/env bash
# Main OMERO/Bio-Formats installation script

set -e
set -u
set -x

export PSQL_DIR=${PSQL_DIR:-/usr/local/var/postgres}
export OMERO_DATA_DIR=${OMERO_DATA_DIR:-/tmp/var/OMERO.data}
export SCRIPT_NAME=${SCRIPT_NAME:-OMERO.sql}
export ROOT_PASSWORD=${ROOT_PASSWORD:-omero}
export ICE=${ICE:-3.5}
export HTTPPORT=${HTTPPORT:-8080}

cd /usr/local

###################################################################
# Bio-Formats installation
###################################################################

# Install Bio-Formats
bin/brew install bioformats51
VERBOSE=1 bin/brew test bioformats51

###################################################################
# OMERO installation
###################################################################

# Install PostgreSQL and OMERO
OMERO_PYTHONPATH=$(bin/brew --prefix omero51)/lib/python
if [ "$ICE" == "3.4" ]; then
    bin/brew install omero51 --with-ice34 --with-nginx --with-cpp
    ICE_HOME=$(bin/brew --prefix zeroc-ice34)
    export PYTHONPATH=$OMERO_PYTHONPATH:$ICE_HOME/python
    export DYLD_LIBRARY_PATH=$ICE_HOME/lib
else
    bin/brew install omero51 --with-nginx --with-cpp
    export PYTHONPATH=$OMERO_PYTHONPATH
fi
VERBOSE=1 bin/brew test omero51

# Install PostgreSQL
bin/brew install postgres

# Install OMERO Python dependencies
bash bin/omero_python_deps

# Set additional environment variables
export ICE_CONFIG=$(bin/brew --prefix omero51)/etc/ice.config

# Note: If postgres startup fails it's probably because there was an old
# process still running.
# Create PostgreSQL database
if [ -d "$PSQL_DIR" ]; then
    rm -rf $PSQL_DIR
fi
bin/initdb -E UTF8 $PSQL_DIR
bin/pg_ctl -D $PSQL_DIR -l $PSQL_DIR/server.log -w start

# Create user and database
bin/createuser -w -D -R -S db_user
bin/createdb -E UTF8 -O db_user omero_database
bin/psql -h localhost -U db_user -l

# Set database
bin/omero config set omero.db.name omero_database
bin/omero config set omero.db.user db_user
bin/omero config set omero.db.pass db_password

# Run DB script
bin/omero db script --password $ROOT_PASSWORD -f $SCRIPT_NAME
bin/psql -h localhost -U db_user omero_database < $SCRIPT_NAME
rm $SCRIPT_NAME

# Set up the data directory
if [ -d "$OMERO_DATA_DIR" ]; then
    rm -rf $OMERO_DATA_DIR
fi
mkdir -p $OMERO_DATA_DIR
bin/omero config set omero.data.dir $OMERO_DATA_DIR

# Start the server
bin/omero admin start

# Check OMERO version
bin/omero version | grep -v UNKNOWN

# Test simple fake import
bin/omero login -s localhost -u root -w $ROOT_PASSWORD
touch test.fake
bin/omero import test.fake
bin/omero logout

# Start OMERO.web
bin/omero config set omero.web.application_server "fastcgi-tcp"
bin/omero config set omero.web.debug True
bin/omero web config nginx-development --http $HTTPPORT > /usr/local/etc/nginx/omero.conf
nginx -c /usr/local/etc/nginx/omero.conf
bin/omero web start

# Test simple Web connection
brew install wget
sleep 10
wget --keep-session-cookies --save-cookies cookies.txt http://localhost:$HTTPPORT/webclient/login/ -O csrf_index.html
csrf=$(cat csrf_index.html | grep "name=\'csrfmiddlewaretoken\'"  | sed "s/.* value=\'\(.*\)\'.*/\1/")
post_data="username=root&password=$ROOT_PASSWORD&csrfmiddlewaretoken=$csrf&server=1&noredirect=1"
resp=$(wget --keep-session-cookies --load-cookies cookies.txt --post-data $post_data http://localhost:$HTTPPORT/webclient/login/)
echo "$resp"

# Stop OMERO.web
bin/omero web stop
nginx -c /usr/local/etc/nginx/omero.conf -s stop

# Stop the server
bin/omero admin stop

# Stop PostgreSQL
bin/pg_ctl -D $PSQL_DIR  -m fast stop
