#!/usr/bin/env bash
# Main OMERO/Bio-Formats installation script

set -e
set -u
set -x

export PSQL_DIR=${PSQL_DIR:-/usr/local/var/postgres}
export OMERO_DATA_DIR=${OMERO_DATA_DIR:-/tmp/var/OMERO.data}
export SCRIPT_NAME=${SCRIPT_NAME:-OMERO.sql}
export ICE=${ICE:-3.5}

cd /usr/local

###################################################################
# Bio-Formats installation
###################################################################

# Install Bio-Formats
bin/brew install bioformats44
showinf -version

###################################################################
# OMERO installation
###################################################################

# Install PostgreSQL and OMERO
OMERO_PYTHONPATH=$(bin/brew --prefix omero)/lib/python
if [ "$ICE" == "3.3" ]; then
    bin/brew install omero44 --with-ice33
    ICE_HOME=$(bin/brew --prefix zeroc-ice33)
    export PYTHONPATH=$OMERO_PYTHONPATH:$ICE_HOME/python
    export DYLD_LIBRARY_PATH=$ICE_HOME/lib
elif [ "$ICE" == "3.4" ]; then
    bin/brew install omero44 --with-ice34
    ICE_HOME=$(bin/brew --prefix zeroc-ice34)
    export PYTHONPATH=$OMERO_PYTHONPATH:$ICE_HOME/python
    export DYLD_LIBRARY_PATH=$ICE_HOME/lib
else
    bin/brew install omero44
    export PYTHONPATH=$OMERO_PYTHONPATH
fi
bin/brew install postgres

# Fix for PIL installation
ln -s /usr/local/include/freetype2 /usr/local/include/freetype

# Install OMERO Python dependencies
bash bin/omero_python_deps

# Set additional environment variables
export ICE_CONFIG=$(bin/brew --prefix omero44)/etc/ice.config

# Note: If postgres startup fails it's probably because there was an old
# process still running.
# Create PostgreSQL database
if [ -d "$PSQL_DIR" ]; then
    rm -rf $PSQL_DIR
fi
bin/initdb $PSQL_DIR
bin/pg_ctl -D $PSQL_DIR -l $PSQL_DIR/server.log -w start

# Create user and database
bin/createuser -w -D -R -S db_user
bin/createdb -O db_user omero_database
bin/psql -h localhost -U db_user -l

# Set database
bin/omero config set omero.db.name omero_database
bin/omero config set omero.db.user db_user
bin/omero config set omero.db.pass db_password

# Run DB script
bin/omero db script "" "" root_password -f $SCRIPT_NAME
bin/psql -h localhost -U db_user omero_database < $SCRIPT_NAME
rm $SCRIPT_NAME

# Set up the data directory
if [ -d "$OMERO_DATA_DIR" ]; then
    rm -rf $OMERO_DATA_DIR
fi
mkdir -p $OMERO_DATA_DIR
bin/omero config set omero.data.dir $OMERO_DATA_DIR

# Start the server
bin/omero admin start

# Test simple fake import
bin/omero login -s localhost -u root -w root_password
touch test.fake
bin/omero import test.fake
bin/omero logout

# Stop the server
bin/omero admin stop

# Stop PostgreSQL
bin/pg_ctl -D $PSQL_DIR  -m fast stop
