#!/bin/bash

OMERO_USER=omero
OMERO_SERVER=/home/omero/OMERO.server
VIRTUALENV=/home/omero/omeroenv
su - ${OMERO_USER} -c "source ${VIRTUALENV}/bin/activate;OMERODIR=${OMERO_SERVER} omero web clearsessions"
