---
name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [rockylinux9, debian10, ubuntu2204]
        pg: [pg13, pg14, pg15, pg16]
        exclude:
          - os: ubuntu2204
            pg: pg13
          - os: debian10
            pg: pg15
          - os: debian10
            pg: pg16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install shunit2
        run: sudo apt-get install -y shunit2
      - name: Build walkthroughs
        run: |
          cd linux
          ./autogenerate.sh
      - name: Build docker image
        run: |
          cd linux/test
          PGVER=$PGVER ./docker-build.sh $ENV
          ./test_services.sh 
        env:
          ENV: ${{ matrix.os }}
          PGVER: ${{ matrix.pg }}
